name: Combine M3U8 Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  combine_m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run combine m3u8 script
      run: python combine_m3u8.py

    - name: Commit combined playlist
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add combined_playlist.m3u8
        git commit -m 'Add combined M3U8 playlist'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
